datasets:
  d16-val:
    image_directory: ../datasets/DAVIS/2016/JPEGImages/480p
    mask_directory: ../datasets/DAVIS/2016/Annotations/480p
  d17-val:
    image_directory: ../datasets/DAVIS/2017/trainval/JPEGImages/480p
    mask_directory: ../datasets/DAVIS/2017/trainval/Annotations/480p
  d17-test:
    image_directory: ../datasets/DAVIS/2017/test-dev/JPEGImages/480p
    mask_directory: ../datasets/DAVIS/2017/test-dev/Annotations/480p
  mose-val:
    image_directory: ../datasets/MOSE/valid/JPEGImages
    mask_directory: ../datasets/MOSE/valid/Annotations
#  lvos-val:
#    image_directory: ../datasets/LVOS/valid/JPEGImages
#    mask_directory: ../datasets/LVOS/valid/Annotations
#  lvos-test:
#    image_directory: ../datasets/LVOS/test/JPEGImages
#    mask_directory: ../datasets/LVOS/test/Annotations
  lv1:
    image_directory: ../datasets/LV1/long_video/JPEGImages
    mask_directory: ../datasets/LV1/long_video/Annotations
  puma:
    image_directory: ../datasets/PuMaVOS/JPEGImages 
    mask_directory: ../datasets/PuMaVOS/Annotations
