datasets:
  d16-val:
    image_directory: ../datasets/DAVIS/2016/JPEGImages/480p
    mask_directory: ../datasets/DAVIS/2016/Annotations/480p
    subset: ../datasets/DAVIS/2017/trainval/ImageSets/2016/val.txt
  d17-val:
    image_directory: ../datasets/DAVIS/2017/trainval/JPEGImages/480p
    mask_directory: ../datasets/DAVIS/2017/trainval/Annotations/480p
    subset: ../datasets/DAVIS/2017/trainval/ImageSets/2017/val.txt
  d17-test:
    image_directory: ../datasets/DAVIS/2017/test-dev/JPEGImages/480p
    mask_directory: ../datasets/DAVIS/2017/test-dev/Annotations/480p
    subset: ../datasets/DAVIS/2017/test-dev/ImageSets/2017/test-dev.txt
  y18-val:
    image_directory: ../datasets/YouTube2018/all_frames/valid_all_frames/JPEGImages
    mask_directory: ../datasets/YouTube2018/valid/Annotations
    json_directory: ../datasets/YouTube2018/valid/meta.json
  y19-val:
    image_directory: ../datasets/YouTube/all_frames/valid_all_frames/JPEGImages
    mask_directory: ../datasets/YouTube/valid/Annotations
    json_directory: ../datasets/YouTube/valid/meta.json
  mose-val:
    image_directory: ../datasets/MOSE/valid/JPEGImages
    mask_directory: ../datasets/MOSE/valid/Annotations
  burst-val:
    image_directory: ../datasets/BURST/frames/val
    json_directory: ../datasets/BURST/val/first_frame_annotations.json
  burst-test:
    image_directory: ../datasets/BURST/frames/test
    json_directory: ../datasets/BURST/test/first_frame_annotations.json
  lvos-val:
    image_directory: ../datasets/LVOS/valid/JPEGImages
    mask_directory: ../datasets/LVOS/valid/Annotations_first_only
  lvos-test:
    image_directory: ../datasets/LVOS/test/JPEGImages
    mask_directory: ../datasets/LVOS/test/Annotations
  lv1:
    image_directory: ../datasets/LV1/long_video/JPEGImages
    mask_directory: ../datasets/LV1/long_video/Annotations
    subset: ../datasets/LV1/long_video/ImageSets/2017/val.txt

exclude:
  lvos-val
  lvos-test
  burst-val