datasets:
  d16-val:
    image_directory: ../datasets/DAVIS/2016/JPEGImages/480p
    mask_directory: ../datasets/DAVIS/2016/Annotations/480p
    subset: ../datasets/DAVIS/2017/trainval/ImageSets/2016/val.txt
  d17-val:
    image_directory: ../datasets/DAVIS/2017/trainval/JPEGImages/480p
    mask_directory: ../datasets/DAVIS/2017/trainval/Annotations/480p
    subset: ../datasets/DAVIS/2017/trainval/ImageSets/2017/val.txt
  d17-test:
    image_directory: ../datasets/DAVIS/2017/test-dev/JPEGImages/480p
    mask_directory: ../datasets/DAVIS/2017/test-dev/Annotations/480p
    subset: ../datasets/DAVIS/2017/test-dev/ImageSets/2017/test-dev.txt
  mose-val:
    image_directory: ../datasets/MOSE/valid/JPEGImages
    mask_directory: ../datasets/MOSE/valid/Annotations
  lvos-val:
    image_directory: ../datasets/LVOS/valid/JPEGImages
    mask_directory: ../datasets/LVOS/valid/Annotations_first_only
  lvos-test:
    image_directory: ../datasets/LVOS/test/JPEGImages
    mask_directory: ../datasets/LVOS/test/Annotations
  lv1:
    image_directory: ../datasets/LV1/long_video/JPEGImages
    mask_directory: ../datasets/LV1/long_video/Annotations
    subset: ../datasets/LV1/long_video/ImageSets/2017/val.txt